services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
    ports:
      - '127.0.0.1:3307:3306'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
volumes:
    mariadb_data: {}